services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    # NOTE: Uncomment the following lines to persist postgres data to a local volume.
    # volumes:
    # - ".data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
